version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: crj-laravel-app
        container_name: crj_app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        networks:
            - crj-network

    web:
        image: nginx:alpine
        container_name: crj_nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - crj-network

    db:
        image: mysql:8.0
        container_name: crj_mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: crj_db
            MYSQL_ROOT_PASSWORD: Ed06RootSecPw
        ports:
            - "3307:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - crj-network

volumes:
    dbdata:

networks:
    crj-network:
        driver: bridge
